name              'nvm'
maintainer        'jmreidy'
maintainer_email  'jmreidy@rzrsharp.net'
license           'MIT'
description       'Installs and configures nvm, the node version manager'
supports          'ubuntu', '>= 12.04'
version           '0.1.0'

depends           'git', '>= 2.1.0'
depends           'curl', '>= 1.1.0'
